categories = [
    "African American Fiction",
    "African American Nonfiction",
    "Analysis",
    "Antiquarian",
    "Antiques",
    "Antiques & Collectibles",
    "Architecture",
    "Art",
    "Beginning Reader",
    "Biography & Autobiography",
    "Biology",
    "Business",
    "Careers",
    "Chemistry",
    "Child Development",
    "Children",
    "Children’s Video",
    "Classic Literature",
    "Comedy",
    "Comic and Graphic Books",
    "Computer Technology",
    "Cooking & Food",
    "Crafts",
    "Crime",
    "Criticism",
    "Current Events",
    "Documentary",
    "Drama",
    "Economics",
    "Education",
    "Engineering",
    "Entertainment",
    "Essays",
    "Ethics",
    "Family & Relationships",
    "Fantasy",
    "Feature Film",
    "Feminist",
    "Fiction",
    "Finance",
    "Folklore",
    "Foreign Language",
    "Foreign Language Study",
    "Foreign Language Study Chinese",
    "Foreign Language Study English",
    "Foreign Language Study French",
    "Foreign Language Study German",
    "Foreign Language Study Italian",
    "Foreign Language Study Japanese",
    "Foreign Language Study Korean",
    "Foreign Language Study Portuguese",
    "Foreign Language Study Spanish",
    "Foreign Language Study Vietnamese",
    "Games",
    "Gardening",
    "Gender Studies",
    "Genealogy",
    "Geography",
    "Grammar & Language Usage",
    "Health & Fitness",
    "Historical Fiction",
    "History",
    "Home Design & Décor",
    "Horror",
    "Human Rights",
    "Humor (Fiction)",
    "Humor (Nonfiction)",
    "IMAX",
    "Instructional",
    "Journalism",
    "Juvenile Fiction",
    "Juvenile Literature",
    "Juvenile Nonfiction",
    "Language Arts",
    "Law",
    "Literary Anthologies",
    "Literary Criticism",
    "Literature",
    "Management",
    "Marketing & Sales",
    "Martial Arts",
    "Mathematics",
    "Media Studies",
    "Medical",
    "Military",
    "Multi-Cultural",
    "Music",
    "Music Video",
    "Music-Sheet",
    "Mystery",
    "Mythology",
    "Nature",
    "New Age",
    "Non-English Fiction",
    "Non-English Nonfiction",
    "Nonfiction",
    "Outdoor Recreation",
    "Performing Arts",
    "Pets",
    "Philosophy",
    "Photography",
    "Physics",
    "Picture Book Fiction",
    "Picture Book Nonfiction",
    "Poetry",
    "Politics",
    "Professional",
    "Psychiatry",
    "Psychiatry & Psychology",
    "Psychology",
    "Recovery",
    "Reference",
    "Report",
    "Research",
    "Romance",
    "Scholarly",
    "Science",
    "Science Fiction",
    "Science Fiction & Fantasy",
    "Self Help",
    "Self-Improvement",
    "Short Stories",
    "Social Media",
    "Sociology",
    "Songbook",
    "Sports & Recreations",
    "Study Aids & Workbooks",
    "Suspense",
    "Technology",
    "Text Book",
    "Thriller",
    "Transportation",
    "Travel",
    "Travel Literature",
    "True Crime",
    "Urban Fiction",
    "Western",
    "Women’s Studies",
    "Writing",
    "Young Adult Fiction",
    "Young Adult Literature",
    "Young Adult Nonfiction"
]
